### PR TITLE
Reordered Logs 

### PR DESCRIPTION
**Pull request by hgmacc**
FG2 Integration is now possible in PermafrostDB. This is not yet a function of SensorDB.

### CODE REVIEW

**Review by nicholas512 — COMMENTED** [review]
what is the advantage in 116fa39af97513d2c3ed7e0262967472d8fb09f2  of using absolute paths?

**Comment by hgmacc** [comment]
This was the result of trial and error - using `src="./js/jquery.min.js"></script>` wasn’t compiling correctly with Maven.

**Comment by nicholas512** [comment]
I think the problem was that in [fcc03b5](https://github.com/geocryology/sensorDb/pull/5/commits/fcc03b56e34c1ab1398348c7e8d882de3cbf8052), you may have inadvertently moved the file up one level.  I could get it to compile but it was not finding files in the browser. When I put it back into `/js/` that fixed the problem.

**Comment by nicholas512** [comment]
anyhow, I ended up cherry-picking the relevant commits and making a new PR (#18) because I wasn't sure how to modify this one.

**Pull request closed without merging**
